In [1]:
import json
import pandas as pd

In [2]:
with open(r'C:\Users\Lenovo\Desktop\大数据软件\project2\dev-v2.0.json','r') as f:  
    data = json.loads(f.read())

In [3]:

dev_data = pd.read_json(r'C:\Users\Lenovo\Desktop\大数据软件\project2\dev-v2.0.json')

In [4]:
dev_data

   version                                               data
0     v2.0  {'title': 'Normans', 'paragraphs': [{'qas': [{...
1     v2.0  {'title': 'Computational_complexity_theory', '...
2     v2.0  {'title': 'Southern_California', 'paragraphs':...
3     v2.0  {'title': 'Sky_(United_Kingdom)', 'paragraphs'...
4     v2.0  {'title': 'Victoria_(Australia)', 'paragraphs'...
5     v2.0  {'title': 'Huguenot', 'paragraphs': [{'qas': [...
6     v2.0  {'title': 'Steam_engine', 'paragraphs': [{'qas...
7     v2.0  {'title': 'Oxygen', 'paragraphs': [{'qas': [{'...
8     v2.0  {'title': '1973_oil_crisis', 'paragraphs': [{'...
9     v2.0  {'title': 'European_Union_law', 'paragraphs': ...
10    v2.0  {'title': 'Amazon_rainforest', 'paragraphs': [...
11    v2.0  {'title': 'Ctenophora', 'paragraphs': [{'qas':...
12    v2.0  {'title': 'Fresno,_California', 'paragraphs': ...
13    v2.0  {'title': 'Packet_switching', 'paragraphs': [{...
14    v2.0  {'title': 'Black_Death', 'paragraphs': [{'qas'...
15    v2.0  {'title': 'Geology', 'paragraphs': [{'qas': [{...
16    v2.0  {'title': 'Pharmacy', 'paragraphs': [{'qas': [...
17    v2.0  {'title': 'Civil_disobedience', 'paragraphs': ...
18    v2.0  {'title': 'Construction', 'paragraphs': [{'qas...
19    v2.0  {'title': 'Private_school', 'paragraphs': [{'q...
20    v2.0  {'title': 'Harvard_University', 'paragraphs': ...
21    v2.0  {'title': 'Jacksonville,_Florida', 'paragraphs...
22    v2.0  {'title': 'Economic_inequality', 'paragraphs':...
23    v2.0  {'title': 'University_of_Chicago', 'paragraphs...
24    v2.0  {'title': 'Yuan_dynasty', 'paragraphs': [{'qas...
25    v2.0  {'title': 'Immune_system', 'paragraphs': [{'qa...
26    v2.0  {'title': 'Intergovernmental_Panel_on_Climate_...
27    v2.0  {'title': 'Prime_number', 'paragraphs': [{'qas...
28    v2.0  {'title': 'Rhine', 'paragraphs': [{'qas': [{'q...
29    v2.0  {'title': 'Scottish_Parliament', 'paragraphs':...
30    v2.0  {'title': 'Islamism', 'paragraphs': [{'qas': [...
31    v2.0  {'title': 'Imperialism', 'paragraphs': [{'qas'...
32    v2.0  {'title': 'Warsaw', 'paragraphs': [{'qas': [{'...
33    v2.0  {'title': 'French_and_Indian_War', 'paragraphs...
34    v2.0  {'title': 'Force', 'paragraphs': [{'qas': [{'q...

In [5]:
import pandas as pd
import json

# 读取SQuAD JSON数据
with open(r'C:\Users\Lenovo\Desktop\大数据软件\project2\dev-v2.0.json', 'r', encoding='utf-8') as f:
    squad_data = json.load(f)

# 将SQuAD JSON数据转换为DataFrame
data = squad_data['data']
rows = []

for i in range(len(data)):
    paragraphs = data[i]['paragraphs']
    for j in range(len(paragraphs)):
        context = paragraphs[j]['context']
        qas = paragraphs[j]['qas']
        for k in range(len(qas)):
            question = qas[k]['question']
            id = qas[k]['id']
            answer_list = qas[k]['answers']
            for l in range(len(answer_list)):
                answer = answer_list[l]['text']
                answer_start = answer_list[l]['answer_start']
                answer_end = answer_start + len(answer)
                row = {'id': id, 'question': question, 'context': context,
                       'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
                rows.append(row)

df = pd.DataFrame(rows, columns=['id', 'question', 'context', 'answer', 'answer_start', 'answer_end'])

# 打印DataFrame
print(df)

                             id  \
0      56ddde6b9a695914005b9628
1      56ddde6b9a695914005b9628
2      56ddde6b9a695914005b9628
3      56ddde6b9a695914005b9628
4      56ddde6b9a695914005b9629
...                         ...
20297  5737aafd1c456719005744ff
20298  5737aafd1c456719005744ff
20299  5737aafd1c456719005744ff
20300  5737aafd1c456719005744ff
20301  5737aafd1c456719005744ff

                                                question  \
0                   In what country is Normandy located?
1                   In what country is Normandy located?
2                   In what country is Normandy located?
3                   In what country is Normandy located?
4                     When were the Normans in Normandy?
...                                                  ...
20297  What is the seldom used force unit equal to on...
20298  What is the seldom used force unit equal to on...
20299  What is the seldom used force unit equal to on...
20300  What is the seldom used force unit equal to on...
20301  What is the seldom used force unit equal to on...

                                                 context  \
0      The Normans (Norman: Nourmands; French: Norman...
1      The Normans (Norman: Nourmands; French: Norman...
2      The Normans (Norman: Nourmands; French: Norman...
3      The Normans (Norman: Nourmands; French: Norman...
4      The Normans (Norman: Nourmands; French: Norman...
...                                                  ...
20297  The pound-force has a metric counterpart, less...
20298  The pound-force has a metric counterpart, less...
20299  The pound-force has a metric counterpart, less...
20300  The pound-force has a metric counterpart, less...
20301  The pound-force has a metric counterpart, less...

                        answer  answer_start  answer_end
0                       France           159         165
1                       France           159         165
2                       France           159         165
3                       France           159         165
4      10th and 11th centuries            94         117
...                        ...           ...         ...
20297                   sthène           665         671
20298                   sthène           665         671
20299                   sthène           665         671
20300                   sthène           665         671
20301                   sthène           665         671

[20302 rows x 6 columns]

In [10]:
df

,id,question,context,answer,answer_start,answer_end
0,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
1,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
2,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
3,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
4,56ddde6b9a695914005b9629,When were the Normans in Normandy?,The Normans (Norman: Nourmands; French: Norman...,10th and 11th centuries,94,117
...,...,...,...,...,...,...
20297,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20298,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20299,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20300,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20301,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671

In [8]:
df1=df.drop_duplicates()

In [9]:
df1

,id,question,context,answer,answer_start,answer_end
0,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
4,56ddde6b9a695914005b9629,When were the Normans in Normandy?,The Normans (Norman: Nourmands; French: Norman...,10th and 11th centuries,94,117
5,56ddde6b9a695914005b9629,When were the Normans in Normandy?,The Normans (Norman: Nourmands; French: Norman...,in the 10th and 11th centuries,87,117
8,56ddde6b9a695914005b962a,From which countries did the Norse originate?,The Normans (Norman: Nourmands; French: Norman...,"Denmark, Iceland and Norway",256,283
12,56ddde6b9a695914005b962b,Who was the Norse leader?,The Normans (Norman: Nourmands; French: Norman...,Rollo,308,313
...,...,...,...,...,...,...
20287,5737aafd1c456719005744fd,What is a very seldom used unit of mass in the...,"The pound-force has a metric counterpart, less...",slug,274,278
20288,5737aafd1c456719005744fd,What is a very seldom used unit of mass in the...,"The pound-force has a metric counterpart, less...",metric slug,267,278
20291,5737aafd1c456719005744fd,What is a very seldom used unit of mass in the...,"The pound-force has a metric counterpart, less...",the metric slug,263,278
20292,5737aafd1c456719005744fe,What seldom used term of a unit of force equal...,"The pound-force has a metric counterpart, less...",kip,712,715
20297,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671

In [11]:
df1.to_csv('val1.csv')

In [21]:
import pandas as pd
import json

# 读取SQuAD JSON数据
with open('val.json', 'r', encoding='utf-8') as f:
    squad_data = json.load(f)

# 将SQuAD JSON数据转换为DataFrame
data = squad_data['data']
rows = []

for i in range(len(data)):
    paragraphs = data[i]['paragraphs']
    for j in range(len(paragraphs)):
        context = paragraphs[j]['context']
        qas = paragraphs[j]['qas']
        for k in range(len(qas)):
            question = qas[k]['question']
            id = qas[k]['id']
            answer_list = qas[k]['answers']
            for l in range(len(answer_list)):
                answer = answer_list[l]['text']
                answer_start = answer_list[l]['answer_start']
                answer_end = answer_start + len(answer)
                row = {'id': id, 'question': question, 'context': context,
                       'answer': answer, 'answer_start': answer_start, 'answer_end': answer_end}
                rows.append(row)

df = pd.DataFrame(rows, columns=['id', 'question', 'context', 'answer', 'answer_start', 'answer_end'])

KeyError: 'data'

In [16]:
df

,id,question,context,answer,answer_start,answer_end
0,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
1,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
2,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
3,56ddde6b9a695914005b9628,In what country is Normandy located?,The Normans (Norman: Nourmands; French: Norman...,France,159,165
4,56ddde6b9a695914005b9629,When were the Normans in Normandy?,The Normans (Norman: Nourmands; French: Norman...,10th and 11th centuries,94,117
...,...,...,...,...,...,...
20297,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20298,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20299,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20300,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671
20301,5737aafd1c456719005744ff,What is the seldom used force unit equal to on...,"The pound-force has a metric counterpart, less...",sthène,665,671